---
title: "R Notebook Starter Template"
author: "Your name here"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---

# 1. Prep data

This is where you can load, clean, merge, and transform dataset as needed, rename variables as needed, make new/derivative variables (ex. age from birthdate).

# 2. Check data

There is where you can double-check your N (i.e., the granularity of your datasets), check for impossible or unlikely values (indicative of error), cross-check variables for inconsistencies, and perform other checks to make sure your data is clean.

# 3. Study variables

Study your data by generating descriptive statistics, counts for categorical variables, and single-variable graphs (i.e., histograms) of your variables.

# 4. Deal with missing data

Identify missing data, document reasons for it, compare elements that are missing data to those that are not, decide on exclusion (e.g., if they are missing the primary exposure or outcome), and impute missing data as needed.

# 5. Explore simple relations and assumptions

Correlation matrix, two-variable plots for relationship of interest, plots to test assumptions

# 6. Prepare a descriptive table

Create descriptive tables (a.k.a., "Table 1") only focusing on the key variables for your project or analysis (unlike the previous stages, where you're familiarizing yourself with entire datasets).

# 7. Test the main hypothesis or hypotheses

Run formal statistical tests, run regression models, generate p-values and confidence intervals

# 8. Build final models and accompanying graphics

Check model assumptions, focus on data presentation, build accompanying graphics

# 9. Perform sensitivity analyses

This is where you should conduct analysis under different decisions you might have made in your analysis. For example, run models with and without outliers, try different values for the parameters, try different ways of imputing missing data, etc.

# 10. Prepare final code documents

Data creation (usually the longest), final tables and figures, additional analyses
